image: node:12

pipelines:
  default:
    - step:
        caches:
          - node
        services:
          - docker
        script:
          - curl -L https://github.com/docker/compose/releases/download/1.24.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
          - chmod +x /usr/local/bin/docker-compose
          - docker-compose up -d
          - npm install
          - npm run lint
          - cp .env.dist .env
          - npm run knex:migrate:latest
          - sh ./ci/start-offline.sh
          - npm run tests
          - sh ./ci/stop-offline.sh
